name: Simple CI/CD

on:
  push:
    branches: [ front_with_backend ]
  pull_request:
    branches: [ front_with_backend ]

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy static HTML
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: FrequencyVisualizationWebAPI/wwwroot/html
          publish_branch: github-pages